# Generated by Django 3.2.7 on 2021-09-04 12:53

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.TextField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('profilePic', models.TextField()),
                ('description', models.TextField()),
                ('joinedDate', models.DateTimeField()),
                ('totalViews', models.BigIntegerField()),
                ('subscriberCount', models.TextField()),
                ('videos', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), size=None)),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.TextField(primary_key=True, serialize=False)),
                ('title', models.TextField()),
                ('description', models.TextField()),
                ('videoThumbnail', models.TextField()),
                ('interactionCount', models.BigIntegerField()),
                ('likeCount', models.BigIntegerField()),
                ('dislikecount', models.BigIntegerField()),
                ('uploadDate', models.DateTimeField()),
                ('datePublished', models.DateTimeField()),
                ('channelID', models.TextField()),
                ('genre', models.TextField()),
                ('comments', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), size=None)),
            ],
        ),
    ]
